name: GCN
loop: true
normalize: true
architecture:
  num_layers: 3
  hidden_channels: 256
  dropout: 0.5
  batch_norm: false
  residual: false

grad_norm: 1.0
optim: adam
lr: 0.002
epochs: 500
log_steps: 1